### ISSUE TITLE
Xero migrates to use SHA2

### ISSUE THREAD

**Issue by nqtien310** [waynerobinson/xeroizer#285] opened 2016-03-08 04:43 UTC
I've just received an email from Xero that warns me about their migration from SHA1 -> SHA2, and I did a check to see if my app can work fine with this new change from Xero.

Unfortunately, I notice that in Xeroizer gem, we're still using `:signature_method => 'RSA-SHA1'`.  (Xeroizer::PartnerApplication#25). And I wonder if we have any patch that addresses this issue or it is sufficient for the new Xero migration.

**Comment by waynerobinson** [comment] 2016-03-08 05:13
You might want to try sub-classing the PartnerApplication class with the new signature method and seeing if that works, if so, I'll release a new version. I don't have an active application to test right now.

**Comment by nqtien310** [comment] 2016-03-08 05:22
@waynerobinson 

I tried and received "OAuth::Signature::UnknownSignatureMethod" error

**Comment by waynerobinson** [comment] 2016-03-08 05:22
What did you swap the signature method out for?

**Comment by waynerobinson** [comment] 2016-03-08 05:23
Wait… I'm not sure the signature method needs to change, just your certificate.

**Comment by nqtien310** [comment] 2016-03-08 05:24
````:signature_method => 'RSA-SHA1'```` -> ````:signature_method => 'RSA-SHA2'````

**Comment by waynerobinson** [comment] 2016-03-08 05:26
From http://developer.xero.com/sha-2-final-notice/ it seems that it's just Xero's TLS certs are changing to SHA2. The latest version of Xeroizer has already been updated to make sure the certificate authorities they're using are listed.

**Comment by nqtien310** [comment] 2016-03-08 05:38
Thanks Wayne, I read your link and looks like Xero just requires me to update the API url to their sandbox SHA2 url, somehow, it still doesn't work 

This is my new Partner Application configuration
````{
:xero_url         => 'https://sha2-api-partner.network.xero.com/api.xro/2.0',
          :site             => 'https://sha2-api-partner.network.xero.com',
          :authorize_url    => 'https://sha2-api.xero.com/oauth/Authorize',
          :signature_method => 'RSA-SHA1
}
````

And this is the error I've got
````OpenSSL::SSL::SSLError (SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed)````

**Comment by waynerobinson** [comment] 2016-03-08 05:39
Yes, that should work, but you will need the latest version of xeroizer.

**Comment by nqtien310** [comment] 2016-03-08 05:50
Thanks Wayne, I'm giving it a try

**Comment by cameronbourgeois** [comment] 2016-03-08 20:52
@nqtien310 I am getting the same error as you now in my production environment.

OpenSSL::SSL::SSLError (SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed)

Did you figure out a solution?

Shame on Xero for making such a change and only warning developers 2 days in advance. Seriously... wtf? Did they get attacked?

**Comment by jnguyen1990** [comment] 2016-03-08 21:00
@nqtien310
I ran into this problem at after updating `Xeroizer` it was solved. I only recently integrated with Xero and received an email yesterday, but they made an announcement earlier in the year. [http://developer.xero.com/sha2-ssl-cert-migration-advisory-notice/](url)

**Comment by artspool-nyc** [comment] 2016-03-08 21:10
@nqtien310: We were scratching our head on this one as well, but it turns out you don't need to change the :signature_method. See the comments from the Xero reps in this thread:
https://community.xero.com/developer/discussion/11526709/

Last week Wayne merged the commit below which allowed us to successfully connect to Xero on the SHA2 test URLs provided by Xero. If are using the current master branch of Xero or have updated your fork with the most recent commits it should work.
https://github.com/waynerobinson/xeroizer/pull/283

If you haven't done so already, I highly recommend getting on Xero's developer updates email list. The monthly developer hangouts are useful as well.
http://developer.xero.com/subscribe-to-the-xero-api-developer-mailing-list/

**Comment by waynerobinson** [comment] 2016-03-08 21:23
Yes, the latest version of Xeroizer should support the new endpoints fine. 

There is no need to change the signature method, they're still using RSA-SHA1 for that as per http://developer.xero.com/documentation/getting-started/private-applications/

**Comment by cameronbourgeois** [comment] 2016-03-08 21:28
Awesome thanks @waynerobinson @artspool-nyc @jnguyen1990 - updating my Xeroizer gem now :+1:

**Comment by nqtien310** [comment] 2016-03-09 00:48
Thanks Wayne,  Upgrade Xeroizer to latest version works like a charm.

**Comment by cameronbourgeois** [comment] 2016-03-09 01:01
Worked a charm for me too :)

**Comment by juliancox** [comment] 2016-03-09 21:13
@cameronbourgeois I was getting this error on Heroku but not on my dev box. Fix for heroku without upgrading is adding the heroku path to ca_file...
Xeroizer::PrivateApplication.new(OAUTH_CONSUMER_KEY, OAUTH_CONSUMER_SECRET, KEYPATH, {:ca_file => '/usr/lib/ssl/certs/ca-certificates.crt'})

**Comment by waynerobinson** [comment] 2016-03-09 22:28
That probably works too. I've been thinking about swapping to `OpenSSL::X509::DEFAULT_CERT_FILE` with the obvious ability to override, but not sure if this would end up breaking things as well given that the now bundled certificate file has everything Xero uses in it.

**Comment by nicholasjgreen** [comment] 2016-03-15 04:05
Hi there Xeroizer community - I just saw that some are looking to start using the SHA-2 test urls. Those SHA-2 test urls were temporary so you could try out SHA-2 before we migrated the main api urls. On the 9th of March we did the migration, so please don't use the temporary urls anymore, they will be retired in April. Also, there is no need to change the signing method. The correct and easiest way to make sure that SHA-2 on SSL is working correctly is to use the latest Xeroizer.

I'm sorry if anyone missed the communications about the SHA-2 migration, but we have been actively telling people for 6 months before the migration. This included several direct emails to developers on our email list, notification on our developer portal and even features in more than one of the developer TV videos we produced.

**Comment by teamice** [comment] 2016-03-17 08:37
Hi, i've also got this issue, 
XeroJob failed with OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed - 0 failed attempts
and i also update the Xeroizer gem to 2.16.4, but my application is still having issue when connecting to api.xero.com.

**Comment by Lukom** [comment] 2016-03-17 11:31
Updated to 2.16.4 and it fixed certs issue, thanks

**Comment by brancusi** [comment] 2016-12-05 23:13
I just started getting a SSL_connect error. Anyone else? Any ideas on how to resolve this?

I can run: `openssl s_client -connect api.xero.com:443 -showcerts -CAfile /etc/ssl/certs/ca-certificates.crt`

from the box and I get a valid: `Verify return code: 0 (ok)`

But from the rails app I am getting: 
```
SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed /usr/local/lib/ruby/2.3.0/net/http.rb:933:in `connect_nonblock'
xero_sync.log — /usr/local/lib/ruby/2.3.0/net/http.rb:933:in `connect'
xero_sync.log — /usr/local/lib/ruby/2.3.0/net/http.rb:863:in `do_start'
xero_sync.log — /usr/local/lib/ruby/2.3.0/net/http.rb:852:in `start'
xero_sync.log — /usr/local/lib/ruby/2.3.0/net/http.rb:1398:in `request'
```

Any ideas?

**Comment by warrenchaudhry** [comment] 2016-12-05 23:50
Getting the same issue, our application was hosted on heroku and did not make any changes for a quite a while.

`SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed`

**Comment by waynerobinson** [comment] 2016-12-05 23:51
Have your own keys expired? The ones you generate on Xero?

**Comment by warrenchaudhry** [comment] 2016-12-05 23:53
keys expiration until 2018.

**Comment by waynerobinson** [comment] 2016-12-05 23:53
Never mind, I just checked our production server and we're getting the same problem. It looks like something is trying SSLv3… which nothing ever should (is is a deprecated and insecure SSL version).

**Comment by waynerobinson** [comment] 2016-12-05 23:54
I personally don't have time to have a look at this in the next couple of days (our production system only generates invoices monthly), could someone here raise a ticket with Xero about it? 

Otherwise I will get to it later this week.

**Comment by brancusi** [comment] 2016-12-05 23:55
Am getting this in the dev app as well so I deleted the app and recreated, new keys and all. Still getting this. 

Posted on xero boards, at least one other is having this issue as well.

**Comment by warrenchaudhry** [comment] 2016-12-05 23:57
someone already raised the issue on Xero [https://community.xero.com/developer/discussion/42070581](https://community.xero.com/developer/discussion/42070581)

**Comment by brancusi** [comment] 2016-12-06 00:05
Please let's all comment on this issue on xero so it gets faster feedback.

**Comment by waynerobinson** [comment] 2016-12-06 00:09
This is a Xeroizer problem and a naive choice I made early on to use a built-in certificate list mostly because of Mac OSX issues with certificates and non-Mac apps. 

I have pushed a version (2.6.15) that includes some small fixes including no longer using the built-in certificates by default.

**Comment by brancusi** [comment] 2016-12-06 00:29
Amazing, thank you! Works!

Really appreciate the great work and support @waynerobinson

**Comment by buggy** [comment] 2016-12-06 00:32
Yes. Big thanks @waynerobinson

**Comment by warrenchaudhry** [comment] 2016-12-06 00:42
Woooooohoooooo... awesome.. thanks @waynerobinson

**Comment by bradseefeld** [comment] 2016-12-14 16:21
Some notes for others that come across this issue and are confused. I think @waynerobinson meant to say the version is tagged as 2.16.5, not 2.6.15; 2.16.5 is working for me.

For some reason in rubygems, this version is timestamped for March 1, 2016. As far as I can tell the date is incorrect. There is no tag in git to confirm, but here is the commit where the version was bumped: https://github.com/waynerobinson/xeroizer/commit/76932e36b22c0cbfc2a1b3d3fbbb0860b1dc2546

<img width="394" alt="screen shot 2016-12-14 at 8 18 30 am" src="https://cloud.githubusercontent.com/assets/305470/21190329/3c60a5ba-c1d6-11e6-961b-bec6109752c2.png">

**Comment by MKKuhn** [comment] 2016-12-15 11:23
Unfortunately it seems the issue is still existent for myself after updating to 2.16.5. The only difference now is that it is random, with it happening some days and not others.

`SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed`

The last occurrence was last night (2016-12-14) 23:45 +02:00.
Checked keys and they are set to only expire in a few years.
Any help on this would be greatly appreciated!

**Closed** 2017-10-19 03:13 UTC
