### ISSUE TITLE
Can't create new tax rate

### ISSUE THREAD

**Issue by IsaacResurreccion** [waynerobinson/xeroizer#461] opened 2018-11-20 00:48 UTC
Hi,

I was attempting to create a new tax rate like so:

```ruby
tax_rate = xero_client.TaxRate.build(name: 'Test Tax Rate', report_tax_type: 'INPUT')
tax_rate.add_tax_component(name: 'Tax Component', rate: '10.0')
tax_rate.save
```

But it just returns ``false``.

After a bit of digging I found that the issue is ultimately caused by `set_primary_key :name` in tax_rate.rb ensuring that `new_record?` always returns `false` for valid tax rates, hence sending an update instead of a create. 

I also found this which helped me [#163](https://github.com/waynerobinson/xeroizer/pull/163).

**Comment by rjaus** [comment] 2021-09-22 04:26
Cannot reproduce, seems fixed now.

**Closed by rjaus** 2021-09-22 04:26 UTC
Labels: bug
